<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../styles/styles.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <title>animegram | welcome</title>
</head>

<body class="bg-gradient">
    <main>
        <div class="home">  
            <div>          
                <img src="../views/images/websiteImg/anime_1.png" alt="">
            </div>
            <div class="home-text">
                <h4>welcome to animegram!</h4><br>
                <p>share your anime fanart illustrations with your friends!</p><br>
                <h6>new to animegram?</h6>
                <a href="signup.php">create an account</a><br>
                <h6>already a member?</h6>
                <a href="login.php">login</a>
            </div>
        </div>        
    </main>
</body>
</html>