<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../styles/styles.css">
    <title>animegram | login page</title>
</head>
<body class="bg-gradient">

    <div class="home">
        <h4>login</h4>
        <?php if (isset($message)) : ?>
            <div><?= $message ?></div>
        <?php endif; ?>
        <div>          
            <img src="../views/images/websiteImg/anime_3.jpg" alt="">
        </div><br>
        <form method="post" action="login.php">
            <input type="text" name="username" placeholder="*username" required><br><br>
            <input type="password" name="password" placeholder="*password" required><br><br>
            <button type="submit" name="log_user">login</button><br>
            <a href="index.php">back</a>
        </form>
    </div>

</body>
</html>