<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles/styles.css">
    <title>animegram | signup page</title>
</head>
<body class="bg-gradient">
    <div class="home">
        <h4>sign up</h4>
        <div>          
            <img src="../views/images/websiteImg/anime_2.jpg" alt="">
        </div><br>
        <form method="post">
            <input type="text" name="username" placeholder="*username" required><br><br>
            <input type="password" name="password" placeholder="*password" required><br><br>
            <input type="email" name="email" placeholder="*email" required><br><br>
            <button type="submit" name="reg_user">create account</button><br>
            <a href="index.php">back</a>
        </form>
    </div>
    <!-- <?php if (isset($registerErrorMsg)): ?>
        <div class="alert alert-info"><?= $registerErrorMsg ?></div>
    <?php endif; ?> -->
    
</body>
</html>